[package]
name = "rosa"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../../libs/rust/base", features = ["rot"] }
lang = { path = "../../libs/rust/lang" }
rot = { path = "../../libs/crypto/rot" }
kecacc = { path = "../../libs/crypto/kecacc" }
riscv-rt = { version = "0.12.0", features = ["single-hart"] }
talc = { version = "4.2.0", default-features = false, features = ["lock_api"] }
