[package]
name = "teetest"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/teetest.rs"
crate-type = ["staticlib"]

[dependencies]
base = { path = "../../libs/rust/base" }
m3core = { path = "../../libs/rust/m3core" }
heapsimple = { path = "../../libs/rust/heapsimple" }
unimux = { path = "../../unimux" }
