[package]
name = "unimux"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/unimux.rs"
crate-type = ["rlib"]

[dependencies]
base = { path = "../libs/rust/base" }
lang = { path = "../libs/rust/lang" }
isr = { path = "../libs/rust/isr" }
mux = { path = "../libs/rust/mux" }
paging = { path = "../libs/rust/paging" }
num_enum = { version = "0.6.1", default-features = false }

[features]
default = []
gem5 = ["base/gem5"]
hw = ["base/hw"]
hw22 = ["base/hw22"]
hw23 = ["base/hw23"]
rots = []

[dependencies.num-traits]
version = "0.2.15"
default-features = false
