[package]
name = "unimux"
version = "0.1.0"
edition = "2021"
build = "../build.rs"

[lib]
path = "src/unimux.rs"
crate-type = ["rlib"]

[dependencies]
base = { path = "../libs/rust/base" }
lang = { path = "../libs/rust/lang" }
isr = { path = "../libs/rust/isr" }
mux = { path = "../libs/rust/mux" }
paging = { path = "../libs/rust/paging" }
num_enum = { version = "0.6.1", default-features = false }

[dependencies.num-traits]
version = "0.2.15"
default-features = false
