dirs = [
    'acceltest',
    'allocator',
    'bench',
    'bsdutils',
    'chantests',
    'coreutils',
    'cppnettests',
    'disktest',
    'dosattack',
    'evilcompute',
    'faulter',
    'filterchain',
    'hashmuxtests',
    'hello',
    'info',
    'libctest',
    'msgchan',
    'netechoserver',
    'noop',
    'parchksum',
    'ping',
    'queue',
    'raser',
    'rasertest',
    'resmngtest',
    'rusthello',
    'rustnettests',
    'ruststandalone',
    'ruststdtest',
    'rustunittests',
    'shell',
    'spammer',
    'standalone',
    'straccmux',
    'timertest',
    'unittests',
    'teetest',
]


def build(gen, env):
    for d in dirs:
        env.sub_build(gen, d)
