image: "registry.hpc.barkhauseninstitut.org/os/m3-ci:latest"

# run the pipeline only for merge requests into dev or master
workflow:
   rules:
     - if: $CI_PIPELINE_SOURCE == "web"
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
     - if: $CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /dev|master/
       when: always
     - when: never

stages:
  - prepare
  - build
  - test
  - cleanup

prepare:
  stage: prepare
  script:
    # ensure that no m3-ci pod is still around
    - kubectl delete -n os pod/m3-ci --now || true
    - kubectl wait -n os --for=delete --timeout=5m pod/m3-ci
    # now (re-)create the pod
    - sh ci/config/pod.sh m3-ci m3-ci | kubectl apply -f -
    - kubectl wait -n os --for=condition=ready --timeout=5m pod/m3-ci
  resource_group: pod

build:
  stage: build
  script:
    - kubectl exec -n os -t m3-ci --
        ./bootstrap.sh $CI_COMMIT_SHA
  resource_group: pod

test:
  stage: test
  allow_failure: true
  script:
    - kubectl exec -n os -t m3-ci -- sh -c "
        ./bootstrap.sh $CI_COMMIT_SHA
          && cd M3
          && nix develop path:. -c
            ./ci/tests/gem5.sh /cache/results/$(date -I)-$CI_COMMIT_SHA
        "
  resource_group: pod

cleanup:
  stage: cleanup
  script:
    - kubectl delete -n os pod/m3-ci --now || true
    - kubectl wait -n os --for=delete --timeout=5m pod/m3-ci
  when: always
  resource_group: pod
