[package]
name = "pager"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/pager.rs"
crate-type = ["staticlib"]

[dependencies]
anyhow = { version = "1.0.93", default-features = false }
bitflags = "2.1.0"
m3 = { path = "../../libs/rust/m3" }
resmng = { path = "../../libs/rust/resmng" }
thread = { path = "../../libs/rust/thread" }
hex = { path = "../../libs/crypto/hex" }
