#include <base/Config.h>

#if __riscv_xlen == 32
OUTPUT_FORMAT("elf32-littleriscv")
#else
OUTPUT_FORMAT("elf64-littleriscv")
#endif

ENTRY(_reset)

MEMORY
{
#if __riscv_xlen == 32
#   if defined(__brom__)
    mem  (rx):     ORIGIN = 0x0b002000, LENGTH = 56K
    data (rw):     ORIGIN = 0x00002000, LENGTH = 4K
#   define DATA_MEM data
#   elif defined(__blau__)
    mem  (rwx):    ORIGIN = 0x00004000, LENGTH = 148K
#   define DATA_MEM mem
#   elif defined(__rosa__)
    mem  (rwx):    ORIGIN = 0x00028000, LENGTH = 268K
#   define DATA_MEM mem
#   elif defined(__rots__)
    mem  (rwx):    ORIGIN = 0x0006C000, LENGTH = 336K
#   define DATA_MEM mem
#   endif
#else
#   if defined(__brom__)
    mem  (rx):     ORIGIN = 0x0b002000, LENGTH = 56K
    data (rw):     ORIGIN = 0x10002000, LENGTH = 4K
#   define DATA_MEM data
#   elif defined(__blau__)
    mem  (rwx):    ORIGIN = 0x10004000, LENGTH = 76K
#   define DATA_MEM mem
#   elif defined(__rosa__)
    mem  (rwx):    ORIGIN = 0x10017000, LENGTH = 256K
#   define DATA_MEM mem
#   elif defined(__rots__)
    mem  (rwx):    ORIGIN = 0x10048000, LENGTH = 256K
#   define DATA_MEM mem
#   endif
#endif
}

PHDRS
{
    reset   PT_LOAD;
    data    PT_LOAD;
    tls     PT_LOAD;
    text    PT_LOAD;
}

#if __riscv_xlen == 32
PROVIDE(baremetal_stack = 0x00004000);
#   if defined(__rots__)
PROVIDE(isr_stack = 0x00006000);
#   endif
#else
PROVIDE(baremetal_stack = 0x10004000);
#   if defined(__rots__)
PROVIDE(isr_stack = 0x10006000);
#   endif
#endif

SECTIONS
{
    .reset :
    {
        KEEP (*(SORT_NONE(.init.reset)))
    } > mem : reset

    .data :
    {
        *(.data)
        *(.data.*)
        *(.sdata .sdata.* .sdata2.* .gnu.linkonce.s.*)
        *(.got.plt*)
        *(.got)
    } > DATA_MEM : data

    .bss :
    {
        *(COMMON*)
        *(.bss*)
        *(.sbss .sbss.* .gnu.linkonce.sb.*)
        // the copy/clear routine requires requires an 4/8-byte alignment
        . = ALIGN(8);
        PROVIDE(_eclear = .);
    } > DATA_MEM : data

    /* Thread Local Storage sections  */
    .tdata :
    {
        PROVIDE_HIDDEN (_tdata_start = .);
        *(.tdata .tdata.* .gnu.linkonce.td.*)
    } > DATA_MEM : tls
    .tbss :
    {
        *(.tbss .tbss.* .gnu.linkonce.tb.*) *(.tcommon)
        PROVIDE_HIDDEN (_tdata_end = .);
    } > DATA_MEM : tls

    .text :
    {
        KEEP (*(SORT_NONE(.init)))
        *(.text*)

#if defined(__rots__)
        . = ALIGN(0x1000);
        PROVIDE(_user_start = .);
        *(.user_text)
        PROVIDE(_user_end = .);
        . = ALIGN(0x1000);
#endif
    } > mem : text

    .rodata :
    {
        *(.rodata*)
        *(.srodata*)
        *(.sdata2 .sdata2.* .gnu.linkonce.s2.*)
        KEEP (*(SORT_NONE(.fini)))
    } > mem : text
}
