#include <base/Config.h>

#if defined(__hw23__) || __riscv_xlen == 32
#   define MEM_OFFSET 0
OUTPUT_FORMAT("elf32-littleriscv")
#else
#   define MEM_OFFSET 0x10000000
OUTPUT_FORMAT("elf64-littleriscv")
#endif

ENTRY(_reset)

MEMORY
{
#if defined(__hw23__)
#   define DATA_MEM mem
#   if defined(__brom__)
    mem  (rx):     ORIGIN = MEM_OFFSET + 0x00004000, LENGTH = 48K
#   elif defined(__blau__)
    mem  (rwx):    ORIGIN = MEM_OFFSET + 0x00010000, LENGTH = 236K
#   elif defined(__rosa__)
    mem  (rwx):    ORIGIN = MEM_OFFSET + 0x0004A000, LENGTH = 212K
#   elif defined(__rots__)
    mem  (rwx):    ORIGIN = MEM_OFFSET + 0x00006000, LENGTH = 276K
#   endif
#else
#   if defined(__brom__)
    mem  (rx):     ORIGIN = 0x0b002000,              LENGTH = 56K
    data (rw):     ORIGIN = MEM_OFFSET + 0x00004000, LENGTH = 4K
#   define DATA_MEM data
#   elif defined(__blau__)
    mem  (rwx):    ORIGIN = MEM_OFFSET + 0x00005000, LENGTH = 144K
#   define DATA_MEM mem
#   elif defined(__rosa__)
    mem  (rwx):    ORIGIN = MEM_OFFSET + 0x00029000, LENGTH = 248K
#   define DATA_MEM mem
#   elif defined(__rots__)
    mem  (rwx):    ORIGIN = MEM_OFFSET + 0x00067000, LENGTH = 512K
#   define DATA_MEM mem
#   endif
#endif
}

PHDRS
{
    text    PT_LOAD;
    data    PT_LOAD;
    tls     PT_LOAD;
}

PROVIDE(baremetal_stack_start = MEM_OFFSET + 0x2000);
PROVIDE(baremetal_stack = MEM_OFFSET + 0x4000);
#if defined(__rots__)
PROVIDE(isr_stack = MEM_OFFSET + 0x6000);
#endif

SECTIONS
{
    .text :
    {
        *(.init.reset*)
        KEEP (*(SORT_NONE(.init)))
        *(.text*)

#if defined(__rots__)
        . = ALIGN(0x1000);
        PROVIDE(_user_start = .);
        *(.user_text)
        PROVIDE(_user_end = .);
        . = ALIGN(0x1000);
#endif
    } > mem : text

    .rodata :
    {
        *(.rodata*)
        *(.srodata*)
        *(.sdata2 .sdata2.* .gnu.linkonce.s2.*)
        KEEP (*(SORT_NONE(.fini)))
    } > mem : text

    .data :
    {
        PROVIDE(__data_start = .);
        *(.data)
        *(.data.*)
        *(.sdata .sdata.* .sdata2.* .gnu.linkonce.s.*)
        *(.got.plt*)
        *(.got)
    } > DATA_MEM : data

    .bss :
    {
        PROVIDE(__bss_start = .);
        *(COMMON*)
        *(.bss*)
        *(.sbss .sbss.* .gnu.linkonce.sb.*)
        // the copy/clear routine requires requires an 4/8-byte alignment
        . = ALIGN(8);
        PROVIDE(__bss_end = .);
    } > DATA_MEM : data

    /* Thread Local Storage sections  */
    .tdata :
    {
        PROVIDE_HIDDEN (_tdata_start = .);
        *(.tdata .tdata.* .gnu.linkonce.td.*)
    } > DATA_MEM : tls
    .tbss :
    {
        *(.tbss .tbss.* .gnu.linkonce.tb.*) *(.tcommon)
        PROVIDE_HIDDEN (_tdata_end = .);
    } > DATA_MEM : tls
}
