[package]
name = "hashpipe"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/hashpipe.rs"
crate-type = ["staticlib"]

[dependencies]
heapsimple = { path = "../../../libs/rust/heapsimple" }
m3core = { path = "../../../libs/rust/m3core" }
m3files = { path = "../../../libs/rust/m3files" }
pipecli = { path = "../../../libs/rust/pipecli" }
unimux = { path = "../../../unimux" }

