#!/usr/bin/env python3

import argparse
import os, sys

if not os.path.isfile('ci/builder.py'):
    print("Please invoke this script from the M3 root directory")
    sys.exit(1)

sys.path.append(os.path.realpath('ci'))
import builder

parser = argparse.ArgumentParser(description='This is the M³ bootstrapper.')
parser.add_argument('--target', nargs='+', default=['gem5', 'hw23'])
parser.add_argument('--isa', nargs='+', default=['riscv32', 'riscv64', 'x86_64'])
parser.add_argument('--build', nargs='+', default=['debug', 'release'])
parser.add_argument('--command', nargs='+', default=['prepare', 'build'])
args = parser.parse_args()

cache_dir = 'build/bootstrap'
if 'prepare' in args.command:
    builder.prepare(targets=args.target, isas=args.isa,
                    cache_dir=cache_dir, incremental=True)
if 'build' in args.command:
    builder.build(targets=args.target, isas=args.isa, builds=args.build,
                  cache_dir=cache_dir, incremental=True)
