#!/usr/bin/env python3

import argparse
import os, sys

if not os.path.isfile('ci/builder.py'):
    print("Please invoke this script from the M3 root directory")
    sys.exit(1)

sys.path.append(os.path.realpath('ci'))
import builder

parser = argparse.ArgumentParser(description='This is the M³ bootstrapper.')
parser.add_argument(
    '--target', nargs='+', default=['gem5', 'hw', 'hw23'],
    help='The targets to build for (gem5, hw, hw23)'
)
parser.add_argument('--isa', nargs='+', default=['riscv32', 'riscv64', 'x86_64'])
parser.add_argument('--build', nargs='+', default=['debug', 'release'])
parser.add_argument('--command', nargs='+', default=['prepare', 'build'])
parser.add_argument('--m3lx', action='store_true', help='Enable M³Linux (requires riscv64)')
parser.add_argument('--jobs', '-j', help='Number of concurrent jobs (CPU count by default)')
args = parser.parse_args()

try:
    cache_dir = 'build/bootstrap'
    if 'prepare' in args.command:
        builder.prepare(targets=args.target, isas=args.isa,
                        cache_dir=cache_dir, incremental=True, m3lx=args.m3lx)
    if 'build' in args.command:
        builder.build(targets=args.target, isas=args.isa, builds=args.build,
                      cache_dir=cache_dir, incremental=True, jobs=args.jobs, m3lx=args.m3lx)
except KeyboardInterrupt:
    pass
