[workspace]
members = [
    "apps/acceltest",
    "apps/bench/aesstream",
    "apps/bench/chancreate",
    "apps/bench/enchash",
    "apps/bench/facever",
    "apps/bench/fs",
    "apps/bench/hashmuxbenchs",
    "apps/bench/hashfile",
    "apps/bench/ipc",
    "apps/bench/imgprocpipe",
    "apps/bench/mem",
    "apps/bench/netlat",
    "apps/bench/noopbench",
    "apps/bench/rustbenchs/rustalgobenchs",
    "apps/bench/rustbenchs/rustmiscbenchs",
    "apps/bench/rustbenchs/rustvfsbenchs",
    "apps/bench/rustnetbenchs",
    "apps/bench/voiceassist/vamic",
    "apps/bench/voiceassist/varcv",
    "apps/bench/ycsb/ycsbclient",
    "apps/chantests",
    "apps/coreutils/hashsum",
    "apps/disktest",
    "apps/hashmuxtests",
    "apps/rotshashtests",
    "apps/info",
    "apps/msgchan/msgchansnd",
    "apps/netechoserver",
    "apps/ping",
    "apps/raser",
    "apps/rasertest",
    "apps/repeater",
    "apps/resmngtest",
    "apps/rusthello",
    "apps/rustnettests",
    "apps/ruststandalone/stdareceiver",
    "apps/ruststandalone/stdasender",
    "apps/ruststandalone/vmtest",
    "apps/ruststdtest",
    "apps/rustunittests/rustalgotests",
    "apps/rustunittests/rustdestrtests",
    "apps/rustunittests/rustmisctests",
    "apps/rustunittests/rustvfstests",
    "apps/spammer",
    "apps/straccmux",
    "apps/teetest",
    "kernel",
    "libs/rust/accel",
    "libs/rust/base",
    "libs/rust/heap",
    "libs/rust/heapsimple",
    "libs/rust/isr",
    "libs/rust/lang",
    "libs/rust/m3",
    "libs/rust/m3core",
    "libs/rust/m3files",
    "libs/rust/mux",
    "libs/rust/paging",
    "libs/rust/pci",
    "libs/rust/pipecli",
    "libs/rust/resmng",
    "libs/rust/thread",
    "libs/rust/vtermcli",
    "m3lx/apps/lxrustbenchs",
    "m3lx/apps/starter",
    "m3lx/apps/tcutest",
    "unimux",
    "rot/brom",
    "rot/blau",
    "rot/rosa",
    "rot/rots",
    "server/disk",
    "server/m3fs",
    "server/net",
    "server/pager",
    "server/pipes",
    "server/root",
    "server/vterm",
    "tilemux",
]
resolver = "2"

[profile.release]
lto = true
panic = 'abort'

[profile.dev]
panic = 'abort'
