[package]
name = "aesstream"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/aesstream.rs"
crate-type = ["staticlib"]

[dependencies]
accel = { path = "../../../libs/rust/accel" }
heapsimple = { path = "../../../libs/rust/heapsimple" }
m3core = { path = "../../../libs/rust/m3core" }
m3files = { path = "../../../libs/rust/m3files" }
unimux = { path = "../../../unimux" }

